server:
    port: 8080
spring:
    application:
        name: books
#    profiles:
#        active: prod
    datasource:
        url: jdbc:h2:mem:lmsdb
        username: sa
        password: ''
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true  
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
#    config:
#        import: optional:configserver:http://localhost:8071/

logging:
  level:
    root: info 
    '[com.lms.books]': info

management:
  endpoints:
    web:
      exposure:
        include: '*'