package com.borntocode.main;

import com.borntocode.main.domain.Person;

public class PersonRecordMain {
	public static void main(String[] args) {
		// Create a new record
		Person person = new Person("Vivek", 35);

		// Accessing Record
		System.out.println("Name :: " + person.name());
		System.out.println("Age :: " + person.age());

		// Using toString method automatically generated by the record
		System.out.println(person);

		// Using equals method automatically generated by the record
		Person anotherPerson = new Person("Vivek", 35);
		System.out.println(person.equals(anotherPerson));
	}
}
